-- Inspected production schema subset, 2026-10-04; isolated PostgreSQL test fixture only.
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; grant usage on schema auth to authenticated; create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table public.wearable_health_imports(
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  connection_id uuid,
  provider text default 'garmin'::text not null,
  provider_mode text default 'assisted_capture'::text not null,
  ingestion_channel text not null,
  health_record_type text not null,
  observation_date date not null,
  captured_at timestamptz default now() not null,
  source_reference text,
  source_asset_metadata jsonb default '{}'::jsonb not null,
  raw_observation jsonb default '{}'::jsonb not null,
  normalized_payload jsonb default '{}'::jsonb not null,
  data_confidence text default 'user_verified'::text not null,
  processing_status text default 'normalized'::text not null,
  readiness_snapshot_id uuid,
  notes text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  raw_payload_id uuid,
  constraint wearable_health_imports_data_confidence_check CHECK ((data_confidence = ANY (ARRAY['reported'::text, 'user_verified'::text, 'calculated'::text, 'estimated'::text, 'ocr_unverified'::text, 'unknown'::text]))),
  constraint wearable_health_imports_health_record_type_check CHECK ((health_record_type = ANY (ARRAY['daily_summary'::text, 'sleep'::text, 'body_battery'::text, 'stress'::text, 'heart_rate'::text, 'hrv'::text, 'respiration'::text, 'weight'::text, 'pulse_ox'::text, 'composite'::text, 'other'::text]))),
  constraint wearable_health_imports_ingestion_channel_check CHECK ((ingestion_channel = ANY (ARRAY['chatgpt_assisted_capture'::text, 'lovable_manual_entry'::text, 'garmin_health_api'::text, 'admin_backfill'::text, 'mock_test'::text]))),
  constraint wearable_health_imports_pkey PRIMARY KEY (id),
  constraint wearable_health_imports_processing_status_check CHECK ((processing_status = ANY (ARRAY['received'::text, 'normalized'::text, 'linked'::text, 'error'::text, 'superseded'::text]))),
  constraint wearable_health_imports_provider_mode_check CHECK ((provider_mode = ANY (ARRAY['assisted_capture'::text, 'official_api'::text, 'manual_entry'::text, 'mock_test'::text]))));
alter table public.wearable_health_imports enable row level security;
create policy fixture_owner_select on public.wearable_health_imports for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_health_imports to authenticated;
grant truncate,references,trigger on public.wearable_health_imports to anon;
create table public.wearable_health_observations(
  id int8 generated by default as identity not null,
  user_id uuid not null,
  health_import_id uuid,
  readiness_snapshot_id uuid,
  provider text default 'garmin'::text not null,
  provider_mode text default 'assisted_capture'::text not null,
  ingestion_channel text not null,
  observation_date date not null,
  metric_code text not null,
  metric_name text,
  observation_scope text default 'daily'::text not null,
  observed_at timestamptz,
  interval_start_at timestamptz,
  interval_end_at timestamptz,
  value_numeric numeric,
  value_text text,
  value_json jsonb,
  unit text,
  data_confidence text default 'user_verified'::text not null,
  source_path text,
  created_at timestamptz default now() not null,
  constraint wearable_health_observations_check CHECK (((value_numeric IS NOT NULL) OR (value_text IS NOT NULL) OR (value_json IS NOT NULL))),
  constraint wearable_health_observations_data_confidence_check CHECK ((data_confidence = ANY (ARRAY['reported'::text, 'user_verified'::text, 'calculated'::text, 'estimated'::text, 'ocr_unverified'::text, 'unknown'::text]))),
  constraint wearable_health_observations_ingestion_channel_check CHECK ((ingestion_channel = ANY (ARRAY['chatgpt_assisted_capture'::text, 'lovable_manual_entry'::text, 'garmin_health_api'::text, 'admin_backfill'::text, 'mock_test'::text]))),
  constraint wearable_health_observations_observation_scope_check CHECK ((observation_scope = ANY (ARRAY['daily'::text, 'sleep_session'::text, 'sleep_stage'::text, 'instant'::text, 'interval'::text, 'summary'::text, 'measurement'::text]))),
  constraint wearable_health_observations_pkey PRIMARY KEY (id),
  constraint wearable_health_observations_provider_mode_check CHECK ((provider_mode = ANY (ARRAY['assisted_capture'::text, 'official_api'::text, 'manual_entry'::text, 'mock_test'::text]))));
alter table public.wearable_health_observations enable row level security;
create policy fixture_owner_select on public.wearable_health_observations for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_health_observations to authenticated;
grant truncate,references,trigger on public.wearable_health_observations to anon;
create table public.wearable_health_daily(
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  health_import_id uuid,
  readiness_snapshot_id uuid,
  provider text default 'garmin'::text not null,
  provider_mode text default 'official_api'::text not null,
  ingestion_channel text not null,
  calendar_date date not null,
  resting_heart_rate_bpm numeric,
  min_heart_rate_bpm numeric,
  max_heart_rate_bpm numeric,
  average_stress_level numeric,
  max_stress_level numeric,
  steps int4,
  intensity_minutes int4,
  active_kcal numeric,
  bmr_kcal numeric,
  raw_payload jsonb default '{}'::jsonb not null,
  data_confidence text default 'reported'::text not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  distance_m numeric,
  active_time_seconds int4,
  moderate_intensity_seconds int4,
  vigorous_intensity_seconds int4,
  steps_goal int4,
  intensity_goal_seconds int4,
  stress_duration_seconds int4,
  rest_stress_duration_seconds int4,
  activity_stress_duration_seconds int4,
  low_stress_duration_seconds int4,
  medium_stress_duration_seconds int4,
  high_stress_duration_seconds int4,
  stress_qualifier text,
  body_battery_current numeric,
  body_battery_charged numeric,
  body_battery_drained numeric,
  spo2_avg_pct numeric,
  spo2_min_pct numeric,
  respiration_avg_brpm numeric,
  respiration_min_brpm numeric,
  constraint wearable_health_daily_data_confidence_check CHECK ((data_confidence = ANY (ARRAY['reported'::text, 'user_verified'::text, 'calculated'::text, 'estimated'::text, 'ocr_unverified'::text, 'unknown'::text]))),
  constraint wearable_health_daily_ingestion_channel_check CHECK ((ingestion_channel = ANY (ARRAY['chatgpt_assisted_capture'::text, 'garmin_health_api'::text, 'admin_backfill'::text, 'mock_test'::text]))),
  constraint wearable_health_daily_pkey PRIMARY KEY (id),
  constraint wearable_health_daily_provider_mode_check CHECK ((provider_mode = ANY (ARRAY['assisted_capture'::text, 'official_api'::text, 'manual_entry'::text, 'mock_test'::text]))));
alter table public.wearable_health_daily enable row level security;
create policy fixture_owner_select on public.wearable_health_daily for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_health_daily to authenticated;
grant truncate,references,trigger on public.wearable_health_daily to anon;
create table public.wearable_sleep_sessions(
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  health_import_id uuid,
  readiness_snapshot_id uuid,
  provider text default 'garmin'::text not null,
  provider_mode text default 'official_api'::text not null,
  ingestion_channel text not null,
  calendar_date date not null,
  sleep_start_at timestamptz,
  sleep_end_at timestamptz,
  total_duration_seconds int4,
  deep_sleep_seconds int4,
  light_sleep_seconds int4,
  rem_sleep_seconds int4,
  awake_seconds int4,
  unmeasurable_seconds int4,
  sleep_score numeric,
  restless_moments_count int4,
  respiration_variation_status text,
  avg_sleep_heart_rate_bpm numeric,
  resting_heart_rate_bpm numeric,
  body_battery_change numeric,
  spo2_avg_pct numeric,
  spo2_min_pct numeric,
  respiration_avg_brpm numeric,
  respiration_min_brpm numeric,
  hrv_last_night_avg_ms numeric,
  hrv_last_night_5min_high_ms numeric,
  skin_temperature_change_c numeric,
  raw_payload jsonb default '{}'::jsonb not null,
  data_confidence text default 'reported'::text not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  constraint wearable_sleep_sessions_data_confidence_check CHECK ((data_confidence = ANY (ARRAY['reported'::text, 'user_verified'::text, 'calculated'::text, 'estimated'::text, 'ocr_unverified'::text, 'unknown'::text]))),
  constraint wearable_sleep_sessions_ingestion_channel_check CHECK ((ingestion_channel = ANY (ARRAY['chatgpt_assisted_capture'::text, 'garmin_health_api'::text, 'admin_backfill'::text, 'mock_test'::text]))),
  constraint wearable_sleep_sessions_pkey PRIMARY KEY (id),
  constraint wearable_sleep_sessions_provider_mode_check CHECK ((provider_mode = ANY (ARRAY['assisted_capture'::text, 'official_api'::text, 'manual_entry'::text, 'mock_test'::text]))));
alter table public.wearable_sleep_sessions enable row level security;
create policy fixture_owner_select on public.wearable_sleep_sessions for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_sleep_sessions to authenticated;
grant truncate,references,trigger on public.wearable_sleep_sessions to anon;
create table public.wearable_hrv_nightly_summaries(
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  health_import_id uuid,
  sleep_session_id uuid,
  provider text default 'garmin'::text not null,
  provider_mode text default 'official_api'::text not null,
  ingestion_channel text not null,
  calendar_date date not null,
  last_night_avg_ms numeric,
  last_night_5min_high_ms numeric,
  status text,
  raw_payload jsonb default '{}'::jsonb not null,
  data_confidence text default 'reported'::text not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  constraint wearable_hrv_nightly_summaries_data_confidence_check CHECK ((data_confidence = ANY (ARRAY['reported'::text, 'user_verified'::text, 'calculated'::text, 'estimated'::text, 'ocr_unverified'::text, 'unknown'::text]))),
  constraint wearable_hrv_nightly_summaries_pkey PRIMARY KEY (id),
  constraint wearable_hrv_nightly_summaries_provider_mode_check CHECK ((provider_mode = ANY (ARRAY['assisted_capture'::text, 'official_api'::text, 'manual_entry'::text, 'mock_test'::text]))));
alter table public.wearable_hrv_nightly_summaries enable row level security;
create policy fixture_owner_select on public.wearable_hrv_nightly_summaries for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_hrv_nightly_summaries to authenticated;
grant truncate,references,trigger on public.wearable_hrv_nightly_summaries to anon;
create table public.wearable_heart_rate_samples(
  id int8 generated by default as identity not null,
  user_id uuid not null,
  health_import_id uuid,
  sleep_session_id uuid,
  provider text default 'garmin'::text not null,
  provider_mode text default 'official_api'::text not null,
  ingestion_channel text not null,
  context text not null,
  recorded_at timestamptz not null,
  heart_rate_bpm numeric not null,
  nominal_resolution_seconds int4,
  resolution_status text default 'official_payload_pending'::text not null,
  raw_payload jsonb default '{}'::jsonb not null,
  created_at timestamptz default now() not null,
  constraint wearable_heart_rate_samples_context_check CHECK ((context = ANY (ARRAY['daily'::text, 'sleep'::text, 'activity'::text, 'unknown'::text]))),
  constraint wearable_heart_rate_samples_pkey PRIMARY KEY (id),
  constraint wearable_heart_rate_samples_provider_mode_check CHECK ((provider_mode = ANY (ARRAY['assisted_capture'::text, 'official_api'::text, 'manual_entry'::text, 'mock_test'::text]))),
  constraint wearable_heart_rate_samples_resolution_status_check CHECK ((resolution_status = ANY (ARRAY['fit_exact'::text, 'documented_by_derived_export'::text, 'observed_to_validate'::text, 'official_payload_validated'::text, 'official_payload_pending'::text]))));
alter table public.wearable_heart_rate_samples enable row level security;
create policy fixture_owner_select on public.wearable_heart_rate_samples for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_heart_rate_samples to authenticated;
grant truncate,references,trigger on public.wearable_heart_rate_samples to anon;
create table public.wearable_hrv_nightly_samples(
  id int8 generated by default as identity not null,
  user_id uuid not null,
  hrv_summary_id uuid,
  sleep_session_id uuid,
  provider text default 'garmin'::text not null,
  ingestion_channel text not null,
  recorded_at timestamptz not null,
  hrv_ms numeric not null,
  nominal_resolution_seconds int4 default 300,
  resolution_status text default 'observed_to_validate'::text not null,
  raw_payload jsonb default '{}'::jsonb not null,
  created_at timestamptz default now() not null,
  constraint wearable_hrv_nightly_samples_pkey PRIMARY KEY (id),
  constraint wearable_hrv_nightly_samples_resolution_status_check CHECK ((resolution_status = ANY (ARRAY['documented_by_derived_export'::text, 'observed_to_validate'::text, 'official_payload_validated'::text, 'official_payload_pending'::text]))));
alter table public.wearable_hrv_nightly_samples enable row level security;
create policy fixture_owner_select on public.wearable_hrv_nightly_samples for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_hrv_nightly_samples to authenticated;
grant truncate,references,trigger on public.wearable_hrv_nightly_samples to anon;
create table public.wearable_stress_samples(
  id int8 generated by default as identity not null,
  user_id uuid not null,
  health_import_id uuid,
  provider text default 'garmin'::text not null,
  provider_mode text default 'official_api'::text not null,
  ingestion_channel text not null,
  recorded_at timestamptz not null,
  stress_value numeric,
  stress_status text default 'measured'::text not null,
  nominal_resolution_seconds int4 default 180,
  resolution_status text default 'documented_by_derived_export'::text not null,
  raw_payload jsonb default '{}'::jsonb not null,
  created_at timestamptz default now() not null,
  constraint wearable_stress_samples_pkey PRIMARY KEY (id),
  constraint wearable_stress_samples_stress_status_check CHECK ((stress_status = ANY (ARRAY['measured'::text, 'off_wrist'::text, 'large_motion'::text, 'not_enough_data'::text, 'recovering_from_exercise'::text, 'unidentified'::text]))));
alter table public.wearable_stress_samples enable row level security;
create policy fixture_owner_select on public.wearable_stress_samples for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_stress_samples to authenticated;
grant truncate,references,trigger on public.wearable_stress_samples to anon;
create table public.wearable_body_battery_samples(
  id int8 generated by default as identity not null,
  user_id uuid not null,
  health_import_id uuid,
  provider text default 'garmin'::text not null,
  provider_mode text default 'official_api'::text not null,
  ingestion_channel text not null,
  recorded_at timestamptz not null,
  body_battery_value numeric not null,
  nominal_resolution_seconds int4,
  resolution_status text default 'official_payload_pending'::text not null,
  raw_payload jsonb default '{}'::jsonb not null,
  created_at timestamptz default now() not null,
  constraint wearable_body_battery_samples_pkey PRIMARY KEY (id));
alter table public.wearable_body_battery_samples enable row level security;
create policy fixture_owner_select on public.wearable_body_battery_samples for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_body_battery_samples to authenticated;
grant truncate,references,trigger on public.wearable_body_battery_samples to anon;
create table public.wearable_respiration_samples(
  id int8 generated by default as identity not null,
  user_id uuid not null,
  health_import_id uuid,
  sleep_session_id uuid,
  provider text default 'garmin'::text not null,
  provider_mode text default 'official_api'::text not null,
  ingestion_channel text not null,
  context text not null,
  recorded_at timestamptz not null,
  breaths_per_minute numeric not null,
  nominal_resolution_seconds int4 default 60,
  resolution_status text default 'observed_to_validate'::text not null,
  raw_payload jsonb default '{}'::jsonb not null,
  created_at timestamptz default now() not null,
  constraint wearable_respiration_samples_context_check CHECK ((context = ANY (ARRAY['sleep'::text, 'daily'::text, 'activity'::text, 'unknown'::text]))),
  constraint wearable_respiration_samples_pkey PRIMARY KEY (id));
alter table public.wearable_respiration_samples enable row level security;
create policy fixture_owner_select on public.wearable_respiration_samples for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_respiration_samples to authenticated;
grant truncate,references,trigger on public.wearable_respiration_samples to anon;
create table public.wearable_spo2_samples(
  id int8 generated by default as identity not null,
  user_id uuid not null,
  health_import_id uuid,
  sleep_session_id uuid,
  provider text default 'garmin'::text not null,
  provider_mode text default 'official_api'::text not null,
  ingestion_channel text not null,
  context text not null,
  recorded_at timestamptz not null,
  spo2_percent numeric not null,
  nominal_resolution_seconds int4 default 60,
  resolution_status text default 'documented_by_derived_export'::text not null,
  raw_payload jsonb default '{}'::jsonb not null,
  created_at timestamptz default now() not null,
  constraint wearable_spo2_samples_context_check CHECK ((context = ANY (ARRAY['sleep'::text, 'daily'::text, 'on_demand'::text, 'unknown'::text]))),
  constraint wearable_spo2_samples_pkey PRIMARY KEY (id));
alter table public.wearable_spo2_samples enable row level security;
create policy fixture_owner_select on public.wearable_spo2_samples for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_spo2_samples to authenticated;
grant truncate,references,trigger on public.wearable_spo2_samples to anon;
create table public.wearable_body_composition_measurements(
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  health_import_id uuid,
  raw_payload_id uuid,
  provider text default 'garmin'::text not null,
  ingestion_channel text not null,
  measured_at timestamptz not null,
  weight_kg numeric,
  body_fat_pct numeric,
  body_water_pct numeric,
  skeletal_muscle_mass_kg numeric,
  bone_mass_kg numeric,
  bmi numeric,
  raw_payload jsonb default '{}'::jsonb not null,
  created_at timestamptz default now() not null,
  constraint wearable_body_composition_measurements_pkey PRIMARY KEY (id));
alter table public.wearable_body_composition_measurements enable row level security;
create policy fixture_owner_select on public.wearable_body_composition_measurements for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_body_composition_measurements to authenticated;
grant truncate,references,trigger on public.wearable_body_composition_measurements to anon;
create table public.wearable_vendor_insights(
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  health_import_id uuid,
  provider text default 'garmin'::text not null,
  provider_mode text default 'official_api'::text not null,
  ingestion_channel text not null,
  insight_code text not null,
  insight_domain text not null,
  observation_date date not null,
  observed_at timestamptz,
  value_numeric numeric,
  value_text text,
  value_json jsonb,
  unit text,
  vendor_calculated bool default true not null,
  api_availability text default 'portal_payload_validation_required'::text not null,
  raw_payload jsonb default '{}'::jsonb not null,
  data_confidence text default 'reported'::text not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  constraint wearable_vendor_insights_api_availability_check CHECK ((api_availability = ANY (ARRAY['confirmed_official_metric_family'::text, 'portal_payload_validation_required'::text, 'not_publicly_confirmed'::text, 'optional_conditions_apply'::text]))),
  constraint wearable_vendor_insights_check CHECK (((value_numeric IS NOT NULL) OR (value_text IS NOT NULL) OR (value_json IS NOT NULL))),
  constraint wearable_vendor_insights_data_confidence_check CHECK ((data_confidence = ANY (ARRAY['reported'::text, 'user_verified'::text, 'calculated'::text, 'estimated'::text, 'ocr_unverified'::text, 'unknown'::text]))),
  constraint wearable_vendor_insights_ingestion_channel_check CHECK ((ingestion_channel = ANY (ARRAY['chatgpt_assisted_capture'::text, 'garmin_health_api'::text, 'admin_backfill'::text, 'mock_test'::text]))),
  constraint wearable_vendor_insights_pkey PRIMARY KEY (id),
  constraint wearable_vendor_insights_provider_mode_check CHECK ((provider_mode = ANY (ARRAY['assisted_capture'::text, 'official_api'::text, 'manual_entry'::text, 'mock_test'::text]))));
alter table public.wearable_vendor_insights enable row level security;
create policy fixture_owner_select on public.wearable_vendor_insights for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_vendor_insights to authenticated;
grant truncate,references,trigger on public.wearable_vendor_insights to anon;
create table public.wearable_sleep_stage_intervals(
  id int8 generated by default as identity not null,
  user_id uuid not null,
  sleep_session_id uuid not null,
  provider text default 'garmin'::text not null,
  ingestion_channel text not null,
  stage_code text not null,
  interval_start_at timestamptz not null,
  interval_end_at timestamptz not null,
  duration_seconds int4 generated always as ((EXTRACT(epoch FROM (interval_end_at - interval_start_at)))::integer) stored,
  data_confidence text default 'reported'::text not null,
  raw_payload jsonb default '{}'::jsonb not null,
  created_at timestamptz default now() not null,
  constraint wearable_sleep_stage_intervals_check CHECK ((interval_end_at > interval_start_at)),
  constraint wearable_sleep_stage_intervals_data_confidence_check CHECK ((data_confidence = ANY (ARRAY['reported'::text, 'user_verified'::text, 'calculated'::text, 'estimated'::text, 'ocr_unverified'::text, 'unknown'::text]))),
  constraint wearable_sleep_stage_intervals_pkey PRIMARY KEY (id),
  constraint wearable_sleep_stage_intervals_stage_code_check CHECK ((stage_code = ANY (ARRAY['awake'::text, 'rem'::text, 'light'::text, 'deep'::text, 'unmeasurable'::text, 'unknown'::text]))));
alter table public.wearable_sleep_stage_intervals enable row level security;
create policy fixture_owner_select on public.wearable_sleep_stage_intervals for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_sleep_stage_intervals to authenticated;
grant truncate,references,trigger on public.wearable_sleep_stage_intervals to anon;
create table public.wearable_provider_raw_payloads(
  id uuid default gen_random_uuid() not null,
  user_id uuid not null,
  provider text default 'garmin'::text not null,
  provider_mode text not null,
  ingestion_channel text not null,
  api_product text not null,
  payload_type text not null,
  external_payload_id text,
  observation_date date,
  received_at timestamptz default now() not null,
  payload_sha256 text,
  raw_payload jsonb not null,
  source_asset_metadata jsonb default '{}'::jsonb not null,
  processing_status text default 'received'::text not null,
  parser_version text,
  notes text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  constraint wearable_provider_raw_payloads_api_product_check CHECK ((api_product = ANY (ARRAY['activity'::text, 'health'::text, 'training'::text, 'connect_iq'::text, 'health_sdk'::text, 'ui_evidence'::text, 'other'::text]))),
  constraint wearable_provider_raw_payloads_ingestion_channel_check CHECK ((ingestion_channel = ANY (ARRAY['chatgpt_assisted_capture'::text, 'garmin_health_api'::text, 'garmin_activity_api'::text, 'fit_manual_upload'::text, 'admin_backfill'::text, 'mock_test'::text]))),
  constraint wearable_provider_raw_payloads_pkey PRIMARY KEY (id),
  constraint wearable_provider_raw_payloads_processing_status_check CHECK ((processing_status = ANY (ARRAY['received'::text, 'normalized'::text, 'linked'::text, 'error'::text, 'superseded'::text]))),
  constraint wearable_provider_raw_payloads_provider_mode_check CHECK ((provider_mode = ANY (ARRAY['assisted_capture'::text, 'official_api'::text, 'manual_entry'::text, 'mock_test'::text]))));
alter table public.wearable_provider_raw_payloads enable row level security;
create policy fixture_owner_select on public.wearable_provider_raw_payloads for select to authenticated using ((select auth.uid())=user_id);
grant all on public.wearable_provider_raw_payloads to authenticated;
grant truncate,references,trigger on public.wearable_provider_raw_payloads to anon;
alter table public.wearable_body_battery_samples add constraint wearable_body_battery_samples_health_import_id_fkey FOREIGN KEY (health_import_id) REFERENCES wearable_health_imports(id) ON DELETE CASCADE;
alter table public.wearable_body_battery_samples add constraint wearable_body_battery_samples_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_body_composition_measurements add constraint wearable_body_composition_measurements_health_import_id_fkey FOREIGN KEY (health_import_id) REFERENCES wearable_health_imports(id) ON DELETE SET NULL;
alter table public.wearable_body_composition_measurements add constraint wearable_body_composition_measurements_raw_payload_id_fkey FOREIGN KEY (raw_payload_id) REFERENCES wearable_provider_raw_payloads(id) ON DELETE SET NULL;
alter table public.wearable_body_composition_measurements add constraint wearable_body_composition_measurements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_health_daily add constraint wearable_health_daily_health_import_id_fkey FOREIGN KEY (health_import_id) REFERENCES wearable_health_imports(id) ON DELETE SET NULL;
alter table public.wearable_health_daily add constraint wearable_health_daily_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_health_imports add constraint wearable_health_imports_raw_payload_id_fkey FOREIGN KEY (raw_payload_id) REFERENCES wearable_provider_raw_payloads(id) ON DELETE SET NULL;
alter table public.wearable_health_imports add constraint wearable_health_imports_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_health_observations add constraint wearable_health_observations_health_import_id_fkey FOREIGN KEY (health_import_id) REFERENCES wearable_health_imports(id) ON DELETE CASCADE;
alter table public.wearable_health_observations add constraint wearable_health_observations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_heart_rate_samples add constraint wearable_heart_rate_samples_health_import_id_fkey FOREIGN KEY (health_import_id) REFERENCES wearable_health_imports(id) ON DELETE CASCADE;
alter table public.wearable_heart_rate_samples add constraint wearable_heart_rate_samples_sleep_session_id_fkey FOREIGN KEY (sleep_session_id) REFERENCES wearable_sleep_sessions(id) ON DELETE SET NULL;
alter table public.wearable_heart_rate_samples add constraint wearable_heart_rate_samples_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_hrv_nightly_samples add constraint wearable_hrv_nightly_samples_hrv_summary_id_fkey FOREIGN KEY (hrv_summary_id) REFERENCES wearable_hrv_nightly_summaries(id) ON DELETE CASCADE;
alter table public.wearable_hrv_nightly_samples add constraint wearable_hrv_nightly_samples_sleep_session_id_fkey FOREIGN KEY (sleep_session_id) REFERENCES wearable_sleep_sessions(id) ON DELETE SET NULL;
alter table public.wearable_hrv_nightly_samples add constraint wearable_hrv_nightly_samples_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_hrv_nightly_summaries add constraint wearable_hrv_nightly_summaries_health_import_id_fkey FOREIGN KEY (health_import_id) REFERENCES wearable_health_imports(id) ON DELETE SET NULL;
alter table public.wearable_hrv_nightly_summaries add constraint wearable_hrv_nightly_summaries_sleep_session_id_fkey FOREIGN KEY (sleep_session_id) REFERENCES wearable_sleep_sessions(id) ON DELETE SET NULL;
alter table public.wearable_hrv_nightly_summaries add constraint wearable_hrv_nightly_summaries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_provider_raw_payloads add constraint wearable_provider_raw_payloads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_respiration_samples add constraint wearable_respiration_samples_health_import_id_fkey FOREIGN KEY (health_import_id) REFERENCES wearable_health_imports(id) ON DELETE CASCADE;
alter table public.wearable_respiration_samples add constraint wearable_respiration_samples_sleep_session_id_fkey FOREIGN KEY (sleep_session_id) REFERENCES wearable_sleep_sessions(id) ON DELETE SET NULL;
alter table public.wearable_respiration_samples add constraint wearable_respiration_samples_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_sleep_sessions add constraint wearable_sleep_sessions_health_import_id_fkey FOREIGN KEY (health_import_id) REFERENCES wearable_health_imports(id) ON DELETE SET NULL;
alter table public.wearable_sleep_sessions add constraint wearable_sleep_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_sleep_stage_intervals add constraint wearable_sleep_stage_intervals_sleep_session_id_fkey FOREIGN KEY (sleep_session_id) REFERENCES wearable_sleep_sessions(id) ON DELETE CASCADE;
alter table public.wearable_sleep_stage_intervals add constraint wearable_sleep_stage_intervals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_spo2_samples add constraint wearable_spo2_samples_health_import_id_fkey FOREIGN KEY (health_import_id) REFERENCES wearable_health_imports(id) ON DELETE CASCADE;
alter table public.wearable_spo2_samples add constraint wearable_spo2_samples_sleep_session_id_fkey FOREIGN KEY (sleep_session_id) REFERENCES wearable_sleep_sessions(id) ON DELETE SET NULL;
alter table public.wearable_spo2_samples add constraint wearable_spo2_samples_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_stress_samples add constraint wearable_stress_samples_health_import_id_fkey FOREIGN KEY (health_import_id) REFERENCES wearable_health_imports(id) ON DELETE CASCADE;
alter table public.wearable_stress_samples add constraint wearable_stress_samples_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.wearable_vendor_insights add constraint wearable_vendor_insights_health_import_id_fkey FOREIGN KEY (health_import_id) REFERENCES wearable_health_imports(id) ON DELETE SET NULL;
alter table public.wearable_vendor_insights add constraint wearable_vendor_insights_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE UNIQUE INDEX wearable_health_daily_source_unique ON public.wearable_health_daily USING btree (user_id, provider, ingestion_channel, calendar_date);
CREATE UNIQUE INDEX wearable_health_imports_capture_reference_unique ON public.wearable_health_imports USING btree (user_id, ingestion_channel, source_reference, health_record_type) WHERE ((source_reference IS NOT NULL) AND (ingestion_channel = 'chatgpt_assisted_capture'::text));
CREATE UNIQUE INDEX wearable_hrv_nightly_summary_source_unique ON public.wearable_hrv_nightly_summaries USING btree (user_id, provider, ingestion_channel, calendar_date);
CREATE UNIQUE INDEX wearable_hrv_summary_source_unique ON public.wearable_hrv_nightly_summaries USING btree (user_id, provider, ingestion_channel, calendar_date);
CREATE UNIQUE INDEX wearable_provider_raw_payload_external_upsert_unique ON public.wearable_provider_raw_payloads USING btree (user_id, provider, ingestion_channel, external_payload_id);
CREATE UNIQUE INDEX wearable_provider_raw_payload_official_hash_unique ON public.wearable_provider_raw_payloads USING btree (user_id, provider, ingestion_channel, api_product, payload_type, payload_sha256) WHERE ((external_payload_id IS NULL) AND (payload_sha256 IS NOT NULL) AND (ingestion_channel = 'garmin_health_api'::text));
CREATE UNIQUE INDEX wearable_sleep_sessions_source_unique ON public.wearable_sleep_sessions USING btree (user_id, provider, ingestion_channel, calendar_date);
CREATE UNIQUE INDEX wearable_vendor_insights_capture_unique ON public.wearable_vendor_insights USING btree (user_id, provider, ingestion_channel, observation_date, insight_code) WHERE (ingestion_channel = 'chatgpt_assisted_capture'::text);

-- Real shared-raw assisted mutation policies retained in production.
create policy raw_assisted_insert on public.wearable_provider_raw_payloads for insert to authenticated
  with check ((select auth.uid())=user_id and ingestion_channel='chatgpt_assisted_capture');
create policy raw_assisted_update on public.wearable_provider_raw_payloads for update to authenticated
  using ((select auth.uid())=user_id and ingestion_channel='chatgpt_assisted_capture')
  with check ((select auth.uid())=user_id and ingestion_channel='chatgpt_assisted_capture');
create policy raw_assisted_delete on public.wearable_provider_raw_payloads for delete to authenticated
  using ((select auth.uid())=user_id and ingestion_channel='chatgpt_assisted_capture');
