export const exerciseCatalog = [
  {
    id: "pallof_press",
    canonical_slug: "pallof_press",
    display_name_es: "Press Pallof",
    display_name_en: "Pallof Press",
    aliases: ["press palof", "pres palof", "pallof", "anti-rotacion con goma", "press antirotacion", "press anti-rotacion"],
    category: "core",
    movement_pattern: "anti_rotation",
    primary_muscles: ["core", "obliques"],
    secondary_muscles: ["glutes"],
    equipment_required: ["band"],
    equipment_optional: ["cable"],
    allowed_measurements: ["reps_per_side", "duration", "sets_reps_load"],
    default_measurement: "reps_per_side",
    difficulty_level: "basic",
    skill_level: "low",
    risk_tags: ["lumbar_safe", "core_control"],
    contraindications: [],
    progressions: ["half_kneeling_pallof_press", "pallof_press_walkout"],
    regressions: ["short_lever_pallof_press"],
    substitutions: ["dead_bug", "side_plank"],
    external_mappings: {},
  },
  {
    id: "front_squat",
    canonical_slug: "front_squat",
    display_name_es: "Sentadilla frontal",
    display_name_en: "Front Squat",
    aliases: ["front squat", "sentadilla frontal", "squat frontal"],
    category: "strength",
    movement_pattern: "squat",
    primary_muscles: ["quadriceps", "glutes"],
    secondary_muscles: ["core", "upper_back"],
    equipment_required: ["barbell"],
    equipment_optional: ["rack"],
    allowed_measurements: ["sets_reps_load", "reps_only"],
    default_measurement: "sets_reps_load",
    difficulty_level: "intermediate",
    skill_level: "medium",
    risk_tags: ["spine_loaded", "mobility_demand"],
    contraindications: [],
    progressions: ["pause_front_squat"],
    regressions: ["goblet_squat"],
    substitutions: ["back_squat", "goblet_squat"],
    external_mappings: {},
  },
  {
    id: "romanian_deadlift",
    canonical_slug: "romanian_deadlift",
    display_name_es: "Peso muerto rumano",
    display_name_en: "Romanian Deadlift",
    aliases: ["rdl", "romanian deadlift", "peso muerto rumano", "pm rumano"],
    category: "strength",
    movement_pattern: "hinge",
    primary_muscles: ["hamstrings", "glutes"],
    secondary_muscles: ["erectors", "upper_back"],
    equipment_required: ["barbell"],
    equipment_optional: ["dumbbells"],
    allowed_measurements: ["sets_reps_load"],
    default_measurement: "sets_reps_load",
    difficulty_level: "intermediate",
    skill_level: "medium",
    risk_tags: ["hinge_pattern", "spine_loaded"],
    contraindications: [],
    progressions: ["deficit_romanian_deadlift"],
    regressions: ["dumbbell_romanian_deadlift"],
    substitutions: ["hip_thrust", "good_morning"],
    external_mappings: {},
  },
  {
    id: "bench_press",
    canonical_slug: "bench_press",
    display_name_es: "Press banca",
    display_name_en: "Bench Press",
    aliases: ["press banca", "bench press", "banca"],
    category: "strength",
    movement_pattern: "horizontal_push",
    primary_muscles: ["chest", "triceps"],
    secondary_muscles: ["front_delts"],
    equipment_required: ["barbell", "bench"],
    equipment_optional: ["rack"],
    allowed_measurements: ["sets_reps_load"],
    default_measurement: "sets_reps_load",
    difficulty_level: "intermediate",
    skill_level: "medium",
    risk_tags: ["shoulder_load"],
    contraindications: [],
    progressions: ["pause_bench_press"],
    regressions: ["push_up"],
    substitutions: ["dumbbell_bench_press", "push_up"],
    external_mappings: {},
  },
  {
    id: "single_arm_row",
    canonical_slug: "single_arm_row",
    display_name_es: "Remo unilateral",
    display_name_en: "Single-arm Row",
    aliases: ["remo unilateral", "remo a una mano", "single arm row", "one arm row"],
    category: "strength",
    movement_pattern: "horizontal_pull",
    primary_muscles: ["lats", "mid_back"],
    secondary_muscles: ["biceps", "rear_delts"],
    equipment_required: ["dumbbell"],
    equipment_optional: ["bench", "cable", "band"],
    allowed_measurements: ["sets_reps_load", "reps_per_side"],
    default_measurement: "sets_reps_load",
    difficulty_level: "basic",
    skill_level: "low",
    risk_tags: ["unilateral"],
    contraindications: [],
    progressions: ["three_point_row"],
    regressions: ["band_row"],
    substitutions: ["seated_row", "ring_row"],
    external_mappings: {},
  },
  {
    id: "wall_ball",
    canonical_slug: "wall_ball",
    display_name_es: "Wall ball",
    display_name_en: "Wall Ball",
    aliases: ["wall ball", "wall balls", "lanzamiento balon pared", "sentadilla con balon"],
    category: "functional",
    movement_pattern: "squat_throw",
    primary_muscles: ["quadriceps", "glutes", "shoulders"],
    secondary_muscles: ["core", "triceps"],
    equipment_required: ["wall_ball"],
    equipment_optional: [],
    allowed_measurements: ["reps_only", "rounds", "amrap_score"],
    default_measurement: "reps_only",
    difficulty_level: "intermediate",
    skill_level: "medium",
    risk_tags: ["overhead", "metabolic"],
    contraindications: [],
    progressions: ["heavier_wall_ball"],
    regressions: ["medicine_ball_squat"],
    substitutions: ["thruster", "air_squat"],
    external_mappings: {},
  },
  {
    id: "rowing_ergometer",
    canonical_slug: "rowing_ergometer",
    display_name_es: "Remo ergometro",
    display_name_en: "Row Ergometer",
    aliases: ["remo ergometro", "remoergometro", "row", "rower", "rowing machine", "remo"],
    category: "cardio",
    movement_pattern: "cyclical_pull",
    primary_muscles: ["cardiorespiratory"],
    secondary_muscles: ["legs", "back"],
    equipment_required: ["rower"],
    equipment_optional: [],
    allowed_measurements: ["cardio_duration_distance", "calories", "power"],
    default_measurement: "cardio_duration_distance",
    difficulty_level: "basic",
    skill_level: "low",
    risk_tags: ["cyclical"],
    contraindications: [],
    progressions: ["interval_row"],
    regressions: ["easy_row"],
    substitutions: ["bike_ergometer", "ski_ergometer"],
    external_mappings: {},
  },
  {
    id: "glute_bridge",
    canonical_slug: "glute_bridge",
    display_name_es: "Puente de gluteo",
    display_name_en: "Glute Bridge",
    aliases: ["puente de gluteo", "glute bridge", "puente gluteo"],
    category: "activation",
    movement_pattern: "hip_extension",
    primary_muscles: ["glutes"],
    secondary_muscles: ["hamstrings", "core"],
    equipment_required: [],
    equipment_optional: ["band"],
    allowed_measurements: ["reps_only", "duration"],
    default_measurement: "reps_only",
    difficulty_level: "basic",
    skill_level: "low",
    risk_tags: ["low_impact"],
    contraindications: [],
    progressions: ["single_leg_glute_bridge"],
    regressions: [],
    substitutions: ["hip_thrust"],
    external_mappings: {},
  },
  {
    id: "dead_bug",
    canonical_slug: "dead_bug",
    display_name_es: "Dead bug",
    display_name_en: "Dead Bug",
    aliases: ["dead bug", "deadbug", "bicho muerto"],
    category: "core",
    movement_pattern: "anti_extension",
    primary_muscles: ["core"],
    secondary_muscles: ["hip_flexors"],
    equipment_required: [],
    equipment_optional: [],
    allowed_measurements: ["reps_per_side", "duration"],
    default_measurement: "reps_per_side",
    difficulty_level: "basic",
    skill_level: "low",
    risk_tags: ["lumbar_safe", "motor_control"],
    contraindications: [],
    progressions: ["loaded_dead_bug"],
    regressions: ["heel_taps"],
    substitutions: ["bird_dog"],
    external_mappings: {},
  },
  {
    id: "bird_dog",
    canonical_slug: "bird_dog",
    display_name_es: "Bird dog",
    display_name_en: "Bird Dog",
    aliases: ["bird dog", "birddog", "perro pajaro"],
    category: "rehab",
    movement_pattern: "anti_rotation",
    primary_muscles: ["core", "glutes"],
    secondary_muscles: ["shoulders"],
    equipment_required: [],
    equipment_optional: [],
    allowed_measurements: ["reps_per_side", "duration"],
    default_measurement: "reps_per_side",
    difficulty_level: "basic",
    skill_level: "low",
    risk_tags: ["low_impact", "motor_control"],
    contraindications: [],
    progressions: ["banded_bird_dog"],
    regressions: ["quadruped_arm_raise"],
    substitutions: ["dead_bug"],
    external_mappings: {},
  },
  {
    id: "diaphragmatic_breathing",
    canonical_slug: "diaphragmatic_breathing",
    display_name_es: "Respiración diafragmática",
    display_name_en: "Diaphragmatic Breathing",
    aliases: ["respiracion diafragmatica", "diafragmatica", "breathing", "respiracion 90/90"],
    category: "breathing",
    movement_pattern: "breathing",
    primary_muscles: ["diaphragm"],
    secondary_muscles: ["parasympathetic"],
    equipment_required: [],
    equipment_optional: [],
    allowed_measurements: ["breathing", "duration"],
    default_measurement: "breathing",
    difficulty_level: "basic",
    skill_level: "low",
    risk_tags: ["recovery"],
    contraindications: [],
    progressions: ["paced_breathing"],
    regressions: [],
    substitutions: ["box_breathing"],
    external_mappings: {},
  },
  {
    id: "lateral_monster_walk",
    canonical_slug: "lateral_monster_walk",
    display_name_es: "Monster walk lateral",
    display_name_en: "Lateral Monster Walk",
    aliases: ["monster walk lateral", "lateral monster walk", "caminar lateral con banda"],
    category: "activation",
    movement_pattern: "lateral_locomotion",
    primary_muscles: ["glute_med"],
    secondary_muscles: ["hips"],
    equipment_required: ["band"],
    equipment_optional: [],
    allowed_measurements: ["reps_per_side", "duration"],
    default_measurement: "reps_per_side",
    difficulty_level: "basic",
    skill_level: "low",
    risk_tags: ["low_impact"],
    contraindications: [],
    progressions: ["heavier_band_monster_walk"],
    regressions: ["side_steps"],
    substitutions: ["clam_shell"],
    external_mappings: {},
  },
];

export function normalizeExerciseName(value) {
  return `${value || ""}`
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function buildExerciseAliasIndex(catalog = exerciseCatalog) {
  const index = new Map();
  catalog.forEach((exercise) => {
    [exercise.canonical_slug, exercise.display_name_es, exercise.display_name_en, ...(exercise.aliases || [])]
      .filter(Boolean)
      .forEach((alias) => index.set(normalizeExerciseName(alias), exercise));
  });
  return index;
}

export function resolveExerciseAlias(value, catalog = exerciseCatalog) {
  const normalized = normalizeExerciseName(value);
  if (!normalized) return null;
  const index = buildExerciseAliasIndex(catalog);
  if (index.has(normalized)) return index.get(normalized);
  return catalog.find((exercise) => normalized.includes(normalizeExerciseName(exercise.display_name_es))) || null;
}
